version: '2'
services:
  mysql:
    image: mysql:5.5
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=directus
      - MYSQL_USER=directus
      - MYSQL_PASSWORD=directus
    # publish mysql server ports to access
    # from outside of container with: mysql -h localhost -P 3306 --protocol=tcp -u directus -p
    # ports:
    #  - "8806:3306"
    # If you need to specify a persistent volume for mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
  directus:
    depends_on:
       - mysql
    image: getdirectus/directus:6.4
    container_name: directus
    # links:
    #  - mysql:mysql
    ports:
     - "80:8080"
    restart: always
    volumes:
    # Switch between named storage, path storage
      # - storage:/var/www/html/storage 
      - ./.data/storage:/var/www/html/storage 
    # Replace ~/Development/directus with your local directus git checkout
    #    - ~/Development/directus:/var/www/html
    environment:
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_DATABASE=directus
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
     - MYSQL_ENV_MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_USER=directus
volumes:
  storage:
    # If you want to define externally, uncomment and adjust as needed
    # external:
    #   name: directus-storage
